### ISSUE TITLE
Unclear argument description

### ISSUE THREAD

**Issue by rbbooth** [mabafaba/koboquest#2]
Help description for "load_questionnaire" argument "choices.label.column.to.use" is unclear as currently written -

choices.label.column.to.use
column header of the column with the choice labels youw want to be used when calling question_get_choice_labels

**Comment by mabafaba** [comment]
thanks!
changed description to:

> choices.label.column.to.use >>> The choices csv file has (sometimes multiple) columns with labels. They are often called "Label::English" or similar. Here you need to provide the _name of the column_ that you want to use for labels (see example!)

Also added an example to the function documentation, guess that would have helped:

```
load_questionnaire(mydata,
                   questions.file="koboquestions.csv",
                   choices.file="kobochoices.csv",
                   choices.label.column.to.use="Label::English")
```
