### ISSUE TITLE
installation fails with R version 3.5.2

### ISSUE THREAD

**Issue by yannsay** [mabafaba/koboquest#5]
Installation of the package fails with R version 3.5.2. Updating R to 3.5.3 solves this.
![github ](https://user-images.githubusercontent.com/12112300/56570629-fa11a800-65c3-11e9-943f-13babea72081.png)

**Comment by mabafaba** [comment]
Worked fine on my machine until I managed to reproduce with packrat. Then tried _everything_ and updating R was the only thing that could resolve it. Thanks Yann!

**Comment by mabafaba** [comment]
Solved: update R to >=3.5.3
